apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmastersp2
spec:
  replicas: 2  # <--- ¡IMPORTANTE! Mínimo 2 para Alta Disponibilidad.
  selector:
    matchLabels:
      app: devmastersp2
  template:
    metadata:
      labels:
        app: devmastersp2
    spec:
      containers:
      - name: contenedor
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: balanceador
spec:
  type: LoadBalancer  # <--- Esto activa la distribución de tráfico
  selector:
    app: devmastersp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
